import { Room, Guest, Reservation, Invoice } from './types';

export const mockRooms: Room[] = [
  {
    id: '1',
    number: '101',
    type: 'single',
    status: 'occupied',
    floor: 1,
    price: 85,
    amenities: ['WiFi', 'TV', 'AC'],
    currentGuest: 'Marie Dubois',
    checkIn: new Date('2024-01-15'),
    checkOut: new Date('2024-01-18'),
    lastCleaned: new Date('2024-01-14'),
  },
  {
    id: '2',
    number: '102',
    type: 'double',
    status: 'available',
    floor: 1,
    price: 120,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar'],
    lastCleaned: new Date('2024-01-15'),
  },
  {
    id: '3',
    number: '103',
    type: 'double',
    status: 'cleaning',
    floor: 1,
    price: 120,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar'],
    lastCleaned: new Date('2024-01-14'),
  },
  {
    id: '4',
    number: '201',
    type: 'suite',
    status: 'occupied',
    floor: 2,
    price: 250,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar', 'Balcony', 'Jacuzzi'],
    currentGuest: 'Jean Martin',
    checkIn: new Date('2024-01-14'),
    checkOut: new Date('2024-01-20'),
    lastCleaned: new Date('2024-01-13'),
  },
  {
    id: '5',
    number: '202',
    type: 'deluxe',
    status: 'available',
    floor: 2,
    price: 180,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar', 'Balcony'],
    lastCleaned: new Date('2024-01-15'),
  },
  {
    id: '6',
    number: '203',
    type: 'double',
    status: 'maintenance',
    floor: 2,
    price: 120,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar'],
    lastCleaned: new Date('2024-01-12'),
  },
  {
    id: '7',
    number: '301',
    type: 'suite',
    status: 'available',
    floor: 3,
    price: 280,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar', 'Balcony', 'Jacuzzi', 'Kitchen'],
    lastCleaned: new Date('2024-01-15'),
  },
  {
    id: '8',
    number: '302',
    type: 'deluxe',
    status: 'occupied',
    floor: 3,
    price: 180,
    amenities: ['WiFi', 'TV', 'AC', 'Minibar', 'Balcony'],
    currentGuest: 'Sophie Laurent',
    checkIn: new Date('2024-01-16'),
    checkOut: new Date('2024-01-19'),
    lastCleaned: new Date('2024-01-15'),
  },
];

export const mockGuests: Guest[] = [
  {
    id: '1',
    firstName: 'Marie',
    lastName: 'Dubois',
    email: 'marie.dubois@email.com',
    phone: '+33 6 12 34 56 78',
    nationality: 'Française',
    idDocument: 'FR123456789',
    birthDate: new Date('1985-03-15'),
    address: '123 Rue de la Paix, Paris 75001',
    loyaltyTier: 'gold',
    totalStays: 8,
    preferences: ['Chambre calme', 'Étage élevé'],
    createdAt: new Date('2023-06-15'),
  },
  {
    id: '2',
    firstName: 'Jean',
    lastName: 'Martin',
    email: 'jean.martin@email.com',
    phone: '+33 6 98 76 54 32',
    nationality: 'Française',
    idDocument: 'FR987654321',
    birthDate: new Date('1978-11-22'),
    address: '456 Avenue des Champs, Lyon 69001',
    loyaltyTier: 'platinum',
    totalStays: 15,
    preferences: ['Suite', 'Service en chambre'],
    createdAt: new Date('2022-03-10'),
  },
  {
    id: '3',
    firstName: 'Sophie',
    lastName: 'Laurent',
    email: 'sophie.laurent@email.com',
    phone: '+33 6 55 44 33 22',
    nationality: 'Française',
    idDocument: 'FR456789123',
    birthDate: new Date('1992-07-08'),
    address: '789 Boulevard Saint-Michel, Marseille 13001',
    loyaltyTier: 'silver',
    totalStays: 4,
    preferences: ['Vue sur mer', 'Balcon'],
    createdAt: new Date('2023-11-20'),
  },
];

export const mockReservations: Reservation[] = [
  {
    id: '1',
    guestId: '1',
    roomId: '1',
    checkIn: new Date('2024-01-15'),
    checkOut: new Date('2024-01-18'),
    guests: 1,
    totalAmount: 255,
    status: 'confirmed',
    paymentStatus: 'paid',
    source: 'online',
    specialRequests: 'Chambre calme s\'il vous plaît',
    createdAt: new Date('2024-01-10'),
    confirmedAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    guestId: '2',
    roomId: '4',
    checkIn: new Date('2024-01-14'),
    checkOut: new Date('2024-01-20'),
    guests: 2,
    totalAmount: 1500,
    status: 'confirmed',
    paymentStatus: 'paid',
    source: 'direct',
    specialRequests: 'Anniversaire de mariage - décoration spéciale',
    createdAt: new Date('2024-01-05'),
    confirmedAt: new Date('2024-01-05'),
  },
  {
    id: '3',
    guestId: '3',
    roomId: '8',
    checkIn: new Date('2024-01-16'),
    checkOut: new Date('2024-01-19'),
    guests: 1,
    totalAmount: 540,
    status: 'confirmed',
    paymentStatus: 'paid',
    source: 'phone',
    createdAt: new Date('2024-01-12'),
    confirmedAt: new Date('2024-01-12'),
  },
  {
    id: '4',
    guestId: '1',
    roomId: '7',
    checkIn: new Date('2024-01-25'),
    checkOut: new Date('2024-01-28'),
    guests: 2,
    totalAmount: 840,
    status: 'pending',
    paymentStatus: 'pending',
    source: 'online',
    specialRequests: 'Arrivée tardive prévue (après 22h)',
    createdAt: new Date('2024-01-18'),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    reservationId: '1',
    guestId: '1',
    items: [
      {
        id: '1',
        description: 'Chambre Single - 3 nuits',
        quantity: 3,
        unitPrice: 85,
        total: 255,
        category: 'room',
      },
    ],
    subtotal: 255,
    tax: 0,
    total: 255,
    paidAmount: 255,
    status: 'paid',
    issueDate: new Date('2024-01-15'),
    dueDate: new Date('2024-01-18'),
    paidDate: new Date('2024-01-15'),
    paymentMethod: 'card',
  },
  {
    id: '2',
    reservationId: '2',
    guestId: '2',
    items: [
      {
        id: '2',
        description: 'Suite - 6 nuits',
        quantity: 6,
        unitPrice: 250,
        total: 1500,
        category: 'room',
      },
    ],
    subtotal: 1500,
    tax: 0,
    total: 1500,
    paidAmount: 1500,
    status: 'paid',
    issueDate: new Date('2024-01-14'),
    dueDate: new Date('2024-01-20'),
    paidDate: new Date('2024-01-14'),
    paymentMethod: 'transfer',
  },
  {
    id: '3',
    reservationId: '3',
    guestId: '3',
    items: [
      {
        id: '3',
        description: 'Chambre Deluxe - 3 nuits',
        quantity: 3,
        unitPrice: 180,
        total: 540,
        category: 'room',
      },
    ],
    subtotal: 540,
    tax: 0,
    total: 540,
    paidAmount: 540,
    status: 'paid',
    issueDate: new Date('2024-01-16'),
    dueDate: new Date('2024-01-19'),
    paidDate: new Date('2024-01-16'),
    paymentMethod: 'cash',
  },
];